apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: techchallenge
data:
  RABBITMQ_HOST: rabbitmq
  USERS_URL: http://users
  GAMES_URL: http://games
  PAYMENTS_URL: http://payments
  ELASTICSEARCH_URL: http://elasticsearch:9200
